version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres.dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    build:
      context: .
      dockerfile: docker/redis.dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge