version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: login-ms
    restart: unless-stopped
    ports:
      - "3500:3000"
    env_file:
      - .env
    networks:
      - backend
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.login-ms.rule=Host(`login-ms.redteslanet.com`)"
      - "traefik.http.routers.login-ms.entrypoints=websecure"
      - "traefik.http.routers.login-ms.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.login-ms.loadbalancer.server.port=3000"

networks:
  backend:
    driver: bridge
  traefik:
    external: true